[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chilly-milly-engine"
version = "0.1.0"
authors = [
    {name = "Dominik Reinartz", email = "dominik.reinartz@hotmail.com"},
]
description = "Game engine for Chilly Milly Games."
readme = "README.md"
requires-python = "==3.9.13"
dependencies = [
    "arcade>=2.6.17",
    "pyglet>=2.0.dev23",
]

[project.optional-dependencies]
dev = [
    "flake8>=6.0.0",
    "isort>=5.12.0",
    "mypy>=1.1.1",
    "pytest>=7.2.2",
    "pytest-cov>=4.0.0",
]