"""
Exports all shape related functions and classes from the arcade module.
Draw multiple shapes at once by putting them into a `ShapeElementList`
for best performance.
"""


from arcade import (Shape, ShapeElementList, create_ellipse,
                    create_ellipse_filled, create_ellipse_filled_with_colors,
                    create_ellipse_outline, create_isometric_grid_lines,
                    create_line, create_line_generic,
                    create_line_generic_with_colors, create_line_loop,
                    create_line_strip, create_lines, create_lines_with_colors,
                    create_polygon, create_rectangle, create_rectangle_filled,
                    create_rectangle_filled_with_colors,
                    create_rectangle_outline,
                    create_rectangles_filled_with_colors,
                    create_triangles_filled_with_colors, draw_arc_filled,
                    draw_arc_outline, draw_circle_filled, draw_circle_outline,
                    draw_ellipse_filled, draw_ellipse_outline, draw_line,
                    draw_line_strip, draw_lines, draw_lrtb_rectangle_filled,
                    draw_lrtb_rectangle_outline, draw_lrwh_rectangle_textured,
                    draw_parabola_filled, draw_parabola_outline, draw_point,
                    draw_points, draw_polygon_filled, draw_polygon_outline,
                    draw_rectangle_filled, draw_rectangle_outline,
                    draw_scaled_texture_rectangle, draw_texture_rectangle,
                    draw_triangle_filled, draw_triangle_outline,
                    draw_xywh_rectangle_filled, draw_xywh_rectangle_outline)

__all__ = [
    "Shape",
    "ShapeElementList",
    "create_ellipse",
    "create_ellipse_filled",
    "create_ellipse_filled_with_colors",
    "create_ellipse_outline",
    "create_isometric_grid_lines",
    "create_line",
    "create_line_generic",
    "create_line_generic_with_colors",
    "create_line_loop",
    "create_line_strip",
    "create_lines",
    "create_lines_with_colors",
    "create_polygon",
    "create_rectangle",
    "create_rectangle_filled",
    "create_rectangle_filled_with_colors",
    "create_rectangle_outline",
    "create_rectangles_filled_with_colors",
    "create_triangles_filled_with_colors",
    "draw_arc_filled",
    "draw_arc_outline",
    "draw_circle_filled",
    "draw_circle_outline",
    "draw_ellipse_filled",
    "draw_ellipse_outline",
    "draw_line",
    "draw_line_strip",
    "draw_lines",
    "draw_lrtb_rectangle_filled",
    "draw_lrtb_rectangle_outline",
    "draw_lrwh_rectangle_textured",
    "draw_parabola_filled",
    "draw_parabola_outline",
    "draw_point",
    "draw_points",
    "draw_polygon_filled",
    "draw_polygon_outline",
    "draw_rectangle_filled",
    "draw_rectangle_outline",
    "draw_scaled_texture_rectangle",
    "draw_texture_rectangle",
    "draw_triangle_filled",
    "draw_triangle_outline",
    "draw_xywh_rectangle_filled",
    "draw_xywh_rectangle_outline",
]
