"""
Exports all shape related functions and classes from the arcade module.
Draw multiple shapes at once by putting them into a `ShapeElementList`
for best performance.
"""


from arcade import (draw_arc_filled, draw_arc_outline, draw_circle_filled,
                    draw_circle_outline, draw_ellipse_filled,
                    draw_ellipse_outline, draw_lbwh_rectangle_filled,
                    draw_lbwh_rectangle_outline, draw_lbwh_rectangle_textured,
                    draw_line, draw_line_strip, draw_lines,
                    draw_lrbt_rectangle_filled, draw_lrbt_rectangle_outline,
                    draw_parabola_filled, draw_parabola_outline, draw_point,
                    draw_points, draw_polygon_filled, draw_polygon_outline,
                    draw_rect_filled, draw_rect_filled_kwargs,
                    draw_rect_outline, draw_rect_outline_kwargs,
                    draw_scaled_texture_rectangle, draw_texture_rectangle,
                    draw_triangle_filled, draw_triangle_outline)
from arcade.isometric import (create_isometric_grid_lines,
                              isometric_grid_to_screen,
                              screen_to_isometric_grid)
from arcade.shape_list import (Shape, ShapeElementList, create_ellipse,
                               create_ellipse_filled,
                               create_ellipse_filled_with_colors,
                               create_ellipse_outline, create_line,
                               create_line_generic,
                               create_line_generic_with_colors,
                               create_line_loop, create_line_strip,
                               create_lines, create_lines_with_colors,
                               create_polygon, create_rectangle,
                               create_rectangle_filled,
                               create_rectangle_filled_with_colors,
                               create_rectangle_outline,
                               create_rectangles_filled_with_colors,
                               create_triangles_filled_with_colors)
from pyglet.shapes import (Arc, Batch, BezierCurve, BorderedRectangle, Box,
                           Circle, Ellipse, Group, Line, Polygon, Rectangle,
                           Sector, ShapeBase, Star, Triangle, Vec2)

__all__ = [
    "Arc",
    "Batch",
    "BezierCurve",
    "BorderedRectangle",
    "Box",
    "Circle",
    "create_ellipse",
    "create_ellipse_filled",
    "create_ellipse_filled_with_colors",
    "create_ellipse_outline",
    "create_isometric_grid_lines",
    "create_line",
    "create_line_generic",
    "create_line_generic_with_colors",
    "create_line_loop",
    "create_line_strip",
    "create_lines",
    "create_lines_with_colors",
    "create_polygon",
    "create_rectangle",
    "create_rectangle_filled",
    "create_rectangle_filled_with_colors",
    "create_rectangle_outline",
    "create_rectangles_filled_with_colors",
    "create_triangles_filled_with_colors",
    "draw_arc_filled",
    "draw_arc_outline",
    "draw_circle_filled",
    "draw_circle_outline",
    "draw_ellipse_filled",
    "draw_ellipse_outline",
    "draw_lbwh_rectangle_filled",
    "draw_lbwh_rectangle_outline",
    "draw_lbwh_rectangle_textured",
    "draw_line",
    "draw_line_strip",
    "draw_lines",
    "draw_lrbt_rectangle_filled",
    "draw_lrbt_rectangle_outline",
    "draw_parabola_filled",
    "draw_parabola_outline",
    "draw_point",
    "draw_points",
    "draw_polygon_filled",
    "draw_polygon_outline",
    "draw_rect_filled",
    "draw_rect_filled_kwargs",
    "draw_rect_outline",
    "draw_rect_outline_kwargs",
    "draw_scaled_texture_rectangle",
    "draw_texture_rectangle",
    "draw_triangle_filled",
    "draw_triangle_outline",
    "Ellipse",
    "Group",
    "isometric_grid_to_screen",
    "Line",
    "Polygon",
    "Rectangle",
    "screen_to_isometric_grid",
    "Sector",
    "Shape",
    "ShapeBase",
    "ShapeElementList",
    "Star",
    "Triangle",
    "Vec2",
]
